== Another Chapter

=== Sub Seciton 1

This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement.

In this chapter, I will give you an example of how to format source code (((source code, formatting, callout))) using AsciiDoctor.

=== See the Source Code Here

.src/01-02/hello-plain/hello.rs
[source,rust,linenums]
----
include::../{sourcedir}/01-02/hello-plain/hello.rs[]
----
<1> Explanation - callout number 1.
<2> Explanation - callout number 2.

For any other source which doesn't relate to source code in programming language, use this: (((source code, formatting, shell display)))

.rustup
[source,bash]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
...
...
----

=== Rust Compilation Process

((Rust compilation process)) can be seen at <<#img-ch01-02-compile-process>>.

[#img-ch01-02-compile-process]
.Rust Compilation Process
[ditaa, target="rust-compilation-process"]
----
 +--------+             +---------+   +--------------+   +----------+   +------------+
 |        |             | Lexing  |   |              |   |          |   |            |
 | Source | Invocation  | and     |   | AST lowering |   | MIR      |   | Code       |
 | code   |------------>| parsing |-->| (HIR)        |-->| lowering |-->| generation |
 |        |             |         |   |              |   |          |   |            |
 +---+----+             +---------+   +--------------+   +----------+   +------------+
----
