== Another Chapter

=== Sub Seciton 1

This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. 

=== See the Source Code Here

[source,rust]
.src/01-02/hello-plain/hello.rs
----
include::../{sourcedir}/01-02/hello-plain/hello.rs[]
----
<1> Explanation - callout number 1.
<2> Explanation - callout number 2.

For any other source which doesn't relate to source code in programming language, use this:

[source,bash]
.rustup
----
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
...
...
----

