== Another Chapter

=== Sub Seciton 1

This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. This is just a statement. 

=== See the Source Code Here

[source,rust,linenums]
.src/01-02/hello-plain/hello.rs
----
include::../{sourcedir}/01-02/hello-plain/hello.rs[]
----
<1> Explanation - callout number 1.
<2> Explanation - callout number 2.

For any other source which doesn't relate to source code in programming language, use this:

[source,bash]
.rustup
----
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
...
...
----

=== Rust Compilation Process

The process can be seen at <<#img-ch01-02-compile-process>>.

[#img-ch01-02-compile-process]
.Rust Compilation Process
[ditaa, target="rust-compilation-process"]
----
 +--------+             +---------+   +--------------+   +----------+   +------------+
 |        |             | Lexing  |   |              |   |          |   |            |
 | Source | Invocation  | and     |   | AST lowering |   | MIR      |   | Code       |
 | code   |------------>| parsing |-->| (HIR)        |-->| lowering |-->| generation |
 |        |             |         |   |              |   |          |   |            |
 +---+----+             +---------+   +--------------+   +----------+   +------------+
----
